### ISSUE TITLE
Implementing Multi-Select Options in YAML Template ？

### ISSUE THREAD

**Issue by Fog3719** [LaunchPlatform/beanhub-cli#4]
I am a Beancount user with limited programming experience, and I'm currently facing a challenge that I hope you can help me with.

I am trying to define a dropdown list in a YAML template, which I am using to organize my data. However, I am unsure of the correct syntax to use for creating a dropdown list that includes multiple options.

Could you please provide me with a simple example or guide on how to set up a dropdown list in a YAML file? I would greatly appreciate any help or resources you could share to assist me in resolving this issue.

```YAML
- name: example-fund-trading-record
  display_name: "Example Fund Trading Record"
  fields:
  - name: date
    type: date
    display_name: "Date"
    required: true
  - name: price
    type: number
    display_name: "Price"
    required: true
  - name: share
    type: number
    display_name: "Share"
    default: "100"
    required: true
  - name: account
    type: account
    display_name: "Account"
    default: 
    creatable: true
    options:
        - option1
        - option2
  - name: bankaccount
    type: str
    display_name: "Bank Account"
    default: "DefaultBank"
  - name: amountspent
    type: number
    display_name: "Amount Spent"
    default: "500"
    required: true
  - name: narration
    type: str
    default: " "
    display_name: "Narration"
  operations: 
  - type: append
    file: "forms/examplefile.beancount"
    content: |
      {{ date }} ! "Online Fund Purchase"  {{ narration | tojson }}
        Assets:Investment:MarketIndex:ExampleFund      {{ share }} ExampleFund { {{ price }} USD ,{{date}} } 
        Assets:Savings:Checking:{{ bankaccount }}                            -{{ amountspent }} USD

```
